export const products = [{
   id: 1,
   name: "Pantalón",
   slug: "pantalon",
   price: 5000,
   image: "https://dolcefilipa.com/pantalones.jpeg",
   stock: 10,
   categories: "Pantalones",
   categoriesIds: 2,
   description: "Pantalón delgado para verano. 90% algodón - 10% poliester.",
   property1: "Tamaño",
   value1: ["S", "M", "L", "XL"],
   property2: "Color",
   value2: ["Rojo", "Amarillo", "Verde"]
},
{
   id: 2,
   name: "Buzo de Alf",
   slug: "buzo-de-alf",
   price: 7000,
   image: "https://dolcefilipa.com/buzo.jpeg",
   stock: 3,
   categories: "Sueters y buzos",
   categoriesIds: 3,
   description: "100% algodón. Grueso.",
   property1: "Tamaño",
   value1: ["S", "M", "L", "XL"],
   property2: "Color",
   value2: ["Rojo", "Amarillo", "Verde"]
},
{
   id: 3,
   name: "Reloj",
   slug: "reloj",
   price: 1500,
   image: "https://dolcefilipa.com/reloj.webp",
   stock: 1,
   categories: "Accesorios",
   categoriesIds: 5,
   description: "Importado de China."
},
{
   id: 4,
   name: "Remera Thumbs up",
   slug: "remera-thumbs-up",
   price: 2500,
   image: "https://dolcefilipa.com/alf-black-white.jpeg",
   stock: 4,
   categories: "Remeras",
   categoriesIds: 1,
   description: "100% algodón.",
   property1: "Tamaño",
   value1: ["S", "M", "L", "XL"],
   property2: "Color",
   value2: ["Rojo", "Amarillo", "Verde"]
},
{
   id: 5,
   name: "Pijama",
   slug: "pijama",
   price: 8000,
   image: "https://dolcefilipa.com/alf-black-white.jpeg",
   stock: 22,
   categories: "Pijamas",
   categoriesIds: 4,
   description: "Nuevo pijama de Alf. Fresco, ideal para verano.",
   property1: "Tamaño",
   value1: ["S", "M", "L", "XL"],
   property2: "Color",
   value2: ["Rojo", "Amarillo", "Verde"]
},
{
   id: 6,
   name: "Sueter talle único",
   slug: "sueter-talle-unico",
   price: 3500,
   image: "https://dolcefilipa.com/alf-black-white.jpeg",
   stock: 6,
   categories: "Sueters y buzos",
   categoriesIds: 3,
   description: "Suéter de hilo. Importado de Estados Unidos"
}];
